### ISSUE TITLE
Issue after site transfer and clean up

### ISSUE THREAD

**Issue by mariobehling** [FOSSASIA-Web/hotelxoai.com#1]
http://opentechsummit.de/hotelxoai/

**Comment by namanyayg** [comment]
Fixed.

**Comment by namangoel1** [comment]
Fixed.

**Comment by tradzik** [comment]
Seems to be still unfixed - images are not displaying on website.

**Comment by roonyh** [comment]
Works fine here on both http://hotelxoai.com/ and http://opentechsummit.de/hotelxoai/ 
@ty221 can you check again?

**Comment by tradzik** [comment]
@RoonyH I rechecked that by flushing cache and I still do not see all images. It is probably, because FILES path is improperly set... I agree - on http://hotelxoai.com/ it works

On my mobile images also don't show.

![xoai](https://cloud.githubusercontent.com/assets/3431139/6349200/427d2154-bc28-11e4-9a7e-722a2d3cb735.JPG)

**Comment by roonyh** [comment]
@ty221 Ah. right. Thanks. But http://opentechsummit.de/hotelxoai/ is not the publicly used URL to this content. Everything works well at  http://hotelxoai.com/ .

**Comment by tradzik** [comment]
@RoonyH Yeah, you're right, I think it shouldn't cause any bigger troubles, I just decided to tell about potentially unfixed issue. Let us wait for @mariobehling opinion to eventually close this issue.

**Comment by mariobehling** [comment]
yes, it only needs to work on hotelxoai.com. Thank you! Closing it.
